Catkin-ProjectName: object_recognition_msgs
Version: 0.1.0
Description: Object_recognition_msgs contains the ROS message and the actionlib definition used in object_recognition_core
Author: Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://www.ros.org/wiki/object_recognition

Depends: catkin, ecto, ecto_ros, genmsg, tabletop

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
